version: '3.4'
services:

  solr1:
    image: solr
    hostname: solr1
    container_name: solr1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
     - 8981:8983
    volumes:
      - ./data/solr1/data:/opt/solr/server/solr/data
      - ./data/solr1/logs:/opt/solr/server/solr/logs
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr

  solr2:
    image: solr

    hostname: solr2
    container_name: solr2
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
     - 8982:8983
    volumes:
      - ./data/solr2/data:/opt/solr/server/solr/data
      - ./data/solr2/logs:/opt/solr/server/solr/logs
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr

  solr3:
    image: solr
    hostname: solr3
    container_name: solr3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - ./data/solr3/data:/opt/solr/server/solr/data
      - ./data/solr3/logs:/opt/solr/server/solr/logs
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    ports:
      - 8983:8983
    networks:
      - solr

  solr_fusion:
    image: solr
    hostname: solr_fusion
    container_name: solr_fusion
    depends_on:
      - zoo_fusion
    volumes:
      - ./data/solr_fusion/data:/opt/solr/server/solr/data
      - ./data/solr_fusion/logs:/opt/solr/server/solr/logs
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo_fusion:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    ports:
      - 8985:8983
    networks:
      - fusion

  zoo1:
    image: zookeeper
    hostname: zoo1
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo2:
    image: zookeeper
    hostname: zoo2
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo3:
    image: zookeeper
    hostname: zoo3
    container_name: zoo3
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      - solr

  zoo_fusion:
    image: zookeeper
    hostname: zoo_fusion
    container_name: zoo_fusion
    restart: always
    ports:
      - 2185:2181
    volumes:
      - ./data/zoo_fusion/data:/data
      - ./data/zoo_fusion/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    networks:
      - fusion

  fusion:
    image: cithub/lwfusion
    hostname: fusion
    container_name: fusion
    environment:
      - FUSION_VER=3.1.0
    depends_on:
      - solr_fusion
    ports:
      - 8091:8091 # agent.port
      - 8765:8765 # api.port
      - 7765:7765 # api.stopPort
      - 8771:8771 # connectors-rpc.port
      - 8984:8984 # connectors-classic.port
      - 7984:7984 # connectors-classic.stopPort
      - 8766:8766 # spark-master.port
      - 8767:8767 # spark-master.uiPort
      - 8769:8769 # spark-worker.port
      - 8770:8770 # spark-worker.uiPort
      - 8763:8763 # admin-ui.port
      - 7763:7763 # admin-ui.stopPort
      - 8768:8768 # sql.port
      - 8780:8780 # webapps.port
      - 7780:7780 # webapps.stopPort
      - 8764:8764 # proxy.port
      - 7764:7764 # proxy.stopPort
    volumes:
      - ./data/fusion/log/admin-ui:/opt/lucidworks/fusion/$FUSION_VER/var/log/admin-ui
      - ./data/fusion/log/agent:/opt/lucidworks/fusion/$FUSION_VER/var/log/agent
      - ./data/fusion/log/api:/opt/lucidworks/fusion/$FUSION_VER/var/log/api
      - ./data/fusion/log/connectors/connectors-rpc:/opt/lucidworks/fusion/$FUSION_VER/var/log/connectors/connectors-rpc
      - ./data/fusion/log/connectors/connectors-classic:/opt/lucidworks/fusion/$FUSION_VER/var/log/connectors/connectors-classic
      - ./data/fusion/log/proxy:/opt/lucidworks/fusion/$FUSION_VER/var/log/proxy
      - ./data/fusion/log/spark-master:/opt/lucidworks/fusion/$FUSION_VER/var/log/spark-master
      - ./data/fusion/log/spark-worker:/opt/lucidworks/fusion/$FUSION_VER/var/log/spark-worker
      - ./data/fusion/log/sql:/opt/lucidworks/fusion/$FUSION_VER/var/log/sql
      - ./data/fusion/log/webapps:/opt/lucidworks/fusion/$FUSION_VER/var/log/webapps
    #   - ./data/fusion/data:/fusion/data
      # - ./data/fusion/var/spark-worker:/fusion/$FUSION_VER/var/spark-worker
      # - ./data/fusion/var/spark-master:/fusion/$FUSION_VER/var/spark-master
      # - ./data/fusion/var/agent:/fusion/$FUSION_VER/var/agent
      # - ./data/fusion/var/api:/fusion/$FUSION_VER/var/api
      # - ./data/fusion/var/connectors:/fusion/$FUSION_VER/var/connectors
      # - ./data/fusion/var/proxy:/fusion/$FUSION_VER/var/proxy
      # - ./data/fusion/var/sql:/fusion/$FUSION_VER/var/sql
      # - ./data/fusion/var/webapps:/fusion/$FUSION_VER/var/webapps
      # - ./data/fusion/var/admin-ui:/fusion/$FUSION_VER/var/admin-ui
      # - ./data/fusion/var/agent:/fusion/$FUSION_VER/var/agent
    command: /bin/bash /opt/lucidworks/fusion/$FUSION_VER/bin/fusion start
    networks:
      - solr
      - fusion
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
networks:
  solr:
  fusion: