version: '3.4'
services:
  solr1:
    image: solr
    container_name: solr1
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: solr1
    depends_on:
      - logstash
    ports:
     - "8981:8983"
    volumes:
      - ./data/solr1/data:/opt/solr/server/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr
      - elastic

  solr2:
    image: solr
    container_name: solr2
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: solr2
    depends_on:
      - logstash
    ports:
     - "8982:8983"
    volumes:
      - ./data/solr2/data:/opt/solr/server/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr
      - elastic

  solr3:
    image: solr
    container_name: solr3
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: solr3
    depends_on:
      - logstash
    volumes:
      - ./data/solr3/data:/opt/solr/server/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    ports:
      - 8983:8983
    networks:
      - solr
      - elastic

  solr4:
    image: solr
    container_name: solr4
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: solr4
    depends_on:
      - logstash
    volumes:
      - ./data/solr4/data:/opt/solr/server/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    ports:
      - 8984:8983
    networks:
      - solr
      - elastic

  solr5:
    image: solr
    container_name: solr5
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: solr5
    depends_on:
      - logstash
    volumes:
      - ./data/solr5/data:/opt/solr/server/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      #- -a
      #- "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    ports:
      - 8985:8983
    networks:
      - solr
      - elastic

  zoo1:
    image: zookeeper
    container_name: zoo1
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr
      - elastic

  zoo2:
    image: zookeeper
    container_name: zoo2
    links:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr
      - elastic

  zoo3:
    image: zookeeper
    container_name: zoo3
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VER}
    container_name: elasticsearch
    environment:
      - cluster.name=elk
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: elasticsearch
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VER}
    container_name: kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5055
        tag: kibana
    volumes:
      - ./data/kibana/data:/usr/share/kibana/data
      - ./data/kibana/logs:/usr/share/kibana/logs
    ports:
      - 5601:5601
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ELASTIC_VER}
    container_name: logstash
    hostname: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
      - ./data/logstash/logs/:/usr/share/logstash/logs/
    ports:
      - 9600:9600
      - 5045:5045
      - 5055:5055
    networks:
      - elastic

networks:
  solr:
    driver: bridge
  elastic:
    driver: bridge