version: '3'
services:
  master:
    container_name: master
    user: hadoop
    build:
      context: .
      dockerfile: Dockerfile-master
    tty: false
    volumes:
      - ./data/master/data:/data
    ports:
      - "3121:22"
      - "8081:8080"
      - "4040:4040"
      - "8888:8888"
    command: ["bin/sh", "/start.sh master"]
  slave1:
    container_name: slave1
    user: hadoop
    build:
      context: .
      dockerfile: Dockerfile-slave
    volumes:
      - ./data/slave1/data:/data
    ports:
      - "3122:22"
      - "8082:8080"
    command: ["bin/sh", "/start.sh"]
  slave2:
    container_name: slave2
    user: root
    build:
      context: .
      dockerfile: Dockerfile-slave
    volumes:
      - ./data/slave2/data:/data
    ports:
      - "3123:22"
      - "8083:8080"
    command: ["bin/sh", "/start.sh"]